version: '3.7'

services:
  product:
    build:
      context: .
      dockerfile: DockerFile
    
    volumes:
      - ./:/app

    expose:
      - 3000
    ports:
      - 3000:3000
    
    command: [yarn, start:dev]
    depends_on:
      - db
    networks:
      - product-db

      
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - product-db
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - product-db

volumes:
  my-db:
networks:
  product-db: